### ISSUE TITLE
Update links/docs to reflect project name change

### ISSUE THREAD

**Issue by mcintyre321** [DiscU/DiscU#3]
Hi, there are a number of links (e.g. the project link from https://www.nuget.org/packages/DiscU/) and documentation pages which point to repos named OneOf, or repos with readme's still labelled OneOf.

I think this is a bit confusing for users of both your package and mine. 
e.g.
https://www.nuget.org/packages/DiscU/ - project link 
https://github.com/DiscU/DiscU - documentation still headed OneOf
https://github.com/Jagged/OneOf - documentation still headed OneOf

**Comment by ghost** [comment]
Hi Harry, thanks for pointing those out!

It looks like James has taken care of all of the DiscU bits.  My old
obsolete fork under Jagged was named after yours and predates the DiscU
stuff.  It's currently read-only and in a few months I'll probably delete
it outright.

Thanks for the original concept!
- Will

**Comment by jamesbascle** [comment]
Fixed in nuspec/readme.  Thanks for info Harry!
